spring.profiles.active=dev


spring.application.name=demo
server.port =8082



spring.autoconfigure.exclude=org.springframework.ai.model.vertexai.autoconfigure.gemini.VertexAiGeminiChatAutoConfiguration

